### ISSUE TITLE
The popup doesn't show anything and right clicking into developer mode shows an error:Error: @vitejs/plugin-react can't detect preamble

### ISSUE THREAD

**Issue by Dieber** [wxt-dev/wxt#1578]
### Describe the bug

The popup doesn't show anything and right clicking into developer mode shows an error:

Error: @vitejs/plugin-react can't detect preamble

snapshots:

![Image](https://github.com/user-attachments/assets/a0815ced-802b-42fd-8278-1c24e43a55db)
![Image](https://github.com/user-attachments/assets/a87d5f61-d690-4d1d-be7c-261b4af1721b)

### Reproduction

bunx wxt@latest init

### Steps to reproduce

Reproduction step:

1.bunx wxt@latest init
2.cd wxt-demo
3.bun i
4.bun dev (bun -b dev also has the same issue)
5.right click on popup
6.open devtool

### System Info

```shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 156.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    bun: 1.2.5 - ~/.bun/bin/bun
  Browsers:
    Chrome: 135.0.7049.85
    Safari: 18.0
  npmPackages:
    wxt: ^0.20.0 => 0.20.1
```

### Used Package Manager

bun

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/wxt-dev/wxt/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://wxt.dev/guide/installation.html).
- [x] Check that there isn't [already an issue](https://github.com/wxt-dev/wxt/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/wxt-dev/wxt/discussions) or join our [Discord Chat Server](https://discord.gg/ZFsZqGery9).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lqhuang** [comment]
The same.

```
System:
    OS: macOS 15.4
    CPU: (10) arm64 Apple M2 Pro
    Memory: 68.31 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.local/state/fnm_multishells/55644_1744550982290/bin/node
    npm: 10.8.2 - ~/.local/state/fnm_multishells/55644_1744550982290/bin/npm
    pnpm: 10.8.0 - ~/.local/state/fnm_multishells/55644_1744550982290/bin/pnpm
  Browsers:
    Chrome: 135.0.7049.85
    Edge: 135.0.3179.73
    Safari: 18.4
  npmPackages:
    react: ^19.1.0 => 19.1.0
    typescript: ^5.8.3 => 5.8.3
    wxt: ^0.20.0 => 0.20.1
```

**Comment by lqhuang** [comment]
What confusing me is everything works normally yesterday (Apr 14, 2025) ??? Problem happened since morning (Apr 15, 2025)

**Comment by Libra-Lei** [comment]
我看到，wxt 昨天发了一个小版本，可以先降级并锁定 0.20.0

**Comment by lqhuang** [comment]
> Wxt released a minor version yesterday. You can downgrade and lock it to 0.20.0 first.

Downgrade version of `wxt` from `"wxt": "^0.20.0"` to `"wxt": "0.20.0"` is work.

@Dieber You could take it a try.

Thanks to @Libra-Lei

**Comment by JohnChan1996** [comment]
> > Wxt released a minor version yesterday. You can downgrade and lock it to 0.20.0 first.Wxt 昨天发布了一个小版本。您可以先降级并锁定到 0.20.0。
> 
> Downgrade version of `wxt` from `"wxt": "^0.20.0"` to `"wxt": "0.20.0"` works.将 `wxt` 的版本从 `"wxt": "^0.20.0"` 降级到 `"wxt": "0.20.0"` 是可行的。
> 
> [@Dieber](https://github.com/Dieber) You could take it a try.您可以试一试。
> 
> Thanks to   感谢[@Libra-Lei](https://github.com/Libra-Lei)

Same problem, same solution.

**Comment by pavitra-infocusp** [comment]
> > > Wxt released a minor version yesterday. You can downgrade and lock it to 0.20.0 first.Wxt 昨天发布了一个小版本。您可以先降级并锁定到 0.20.0。
> > 
> > 
> > Downgrade version of `wxt` from `"wxt": "^0.20.0"` to `"wxt": "0.20.0"` works.将 `wxt` 的版本从 `"wxt": "^0.20.0"` 降级到 `"wxt": "0.20.0"` 是可行的。
> > [@Dieber](https://github.com/Dieber) You could take it a try.您可以试一试。
> > Thanks to   感谢[@Libra-Lei](https://github.com/Libra-Lei)
> 
> Same problem, same solution.

Same problem, same solution. 😂

**Comment by pavi2410** [comment]
> Is this react only?

Not sure if it's react only, but this is an issue with the react module for sure.

**Comment by mengxi-ream** [comment]
> > > Wxt released a minor version yesterday. You can downgrade and lock it to 0.20.0 first.Wxt 昨天发布了一个小版本。您可以先降级并锁定到 0.20.0。
> > 
> > 
> > Downgrade version of `wxt` from `"wxt": "^0.20.0"` to `"wxt": "0.20.0"` works.将 `wxt` 的版本从 `"wxt": "^0.20.0"` 降级到 `"wxt": "0.20.0"` 是可行的。
> > [@Dieber](https://github.com/Dieber) You could take it a try.您可以试一试。
> > Thanks to   感谢[@Libra-Lei](https://github.com/Libra-Lei)
> 
> Same problem, same solution.

same, may need to fix the bug from 0.20.1

**Comment by This-is-Prateek** [comment]
> > > > Wxt released a minor version yesterday. You can downgrade and lock it to 0.20.0 first.Wxt 昨天发布了一个小版本。您可以先降级并锁定到 0.20.0。
> > > 
> > > 
> > > Downgrade version of `wxt` from `"wxt": "^0.20.0"` to `"wxt": "0.20.0"` works.将 `wxt` 的版本从 `"wxt": "^0.20.0"` 降级到 `"wxt": "0.20.0"` 是可行的。
> > > [@Dieber](https://github.com/Dieber) You could take it a try.您可以试一试。
> > > Thanks to   感谢[@Libra-Lei](https://github.com/Libra-Lei)
> > 
> > 
> > Same problem, same solution.
> 
> Same problem, same solution. 😂
> 
> Downgrading wxt from `0.20.1` to `0.20.0` worked.

I am using 0.20.0, but still getting the same error, and the popup is empty.

**Comment by Muzych** [comment]
same here

**Comment by marcellino-ornelas** [comment]
I just started experiencing this but only after I tried to install a node module. 

were using turboJS, react, npm workspaces

```bash
npm install -D @wxt-dev/auto-icons -w apps/chrome-extension
```

**Comment by aklinker1** [comment]
Fix released in [v0.20.2](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.20.2), thanks for the fix @SimYunSup !

**Comment by mengxi-ream** [comment]
Hi, the problem persists @aklinker1 . reproduction: https://github.com/mengxi-ream/wxt-popup-bug

**Comment by aklinker1** [comment]
@mengxi-ream Could you try this version for me?

```sh
npm i https://pkg.pr.new/wxt@b0f4ac82
```

https://github.com/wxt-dev/wxt/commit/b0f4ac82215170444858ab56aab1b1f06a5a35eb

I've confirmed it fixes your reproduction.

I'll release once confirmed

**Comment by SimYunSup** [comment]
@aklinker1 I sincerely apologize for submitting the pull request with the faulty fix. It seemed okay during my testing.

**Comment by mengxi-ream** [comment]
> [@mengxi-ream](https://github.com/mengxi-ream) Could you try this version for me?
> 
> npm i https://pkg.pr.new/wxt@b0f4ac82
> [b0f4ac8](https://github.com/wxt-dev/wxt/commit/b0f4ac82215170444858ab56aab1b1f06a5a35eb)
> 
> I've confirmed it fixes your reproduction.

This works, thank you @aklinker1  @SimYunSup

**Comment by aklinker1** [comment]
OK, fixed fr: https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.20.3

**Comment by Silbad** [comment]
Hello, hum, sorry. Same issue with 0.20.3, test with Firefox + Svelte
```
  "devDependencies": {
    "@tsconfig/svelte": "^5.0.4",
    "@wxt-dev/module-svelte": "^2.0.3",
    "svelte": "^5.28.1",
    "svelte-check": "^4.1.6",
    "tslib": "^2.8.1",
    "typescript": "^5.8.3",
    "wxt": "^0.20.3"
  }
```
![bug](https://i.imgur.com/IVvh95a.png)
Ad ok if downgraded to 0.20.0
Thanks

**Comment by lqhuang** [comment]
> Hello, hum, sorry. Same issue with 0.20.3, test with Firefox + Svelte
> 
>   "devDependencies": {
>     "@tsconfig/svelte": "^5.0.4",
>     "@wxt-dev/module-svelte": "^2.0.3",
>     "svelte": "^5.28.1",
>     "svelte-check": "^4.1.6",
>     "tslib": "^2.8.1",
>     "typescript": "^5.8.3",
>     "wxt": "^0.20.3"
>   }
> 
> ![bug](https://camo.githubusercontent.com/1001c2bb6feddb711bf928bccabfc8ca7815ad28f016b3e01970c2836d5b0bee/68747470733a2f2f692e696d6775722e636f6d2f495676683935612e706e67) And ok if downgraded to 0.20.0 Thanks

`0.20.3` works in my case (wxt + React). It may cause by different reasons. @Silbad Would you mind providing more context info, e.g.: console output in Dev Tools (trigger by F12)

**Comment by Silbad** [comment]
Yes indeed, the error seems different : 

![https://i.imgur.com/uZUkUwH.png](https://i.imgur.com/uZUkUwH.png)

However, I haven't changed anything in the default template
Thanks
